# Generated by Django 5.2.2 on 2025-10-24 08:49

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_account_funnykey_account_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name=myapp.models.User),
        ),
    ]
