# Generated by Django 5.2.2 on 2025-11-12 13:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 11, 12, 13, 41, 26, 467451, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
