# Generated by Django 5.2.2 on 2025-11-13 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_orderitem_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order_date',
        ),
    ]
